---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: terraform-oc-login
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: CLI
    tekton.dev/tags: cli
    tekton.dev/displayName: "terraform cli"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    terraform to oc login
  workspaces:
  - name: state-dir
  params:
  - name: extract-kube-admin-password
    type: string
  - name: extract-kube-admin-username
    type: string
  - name: extract-api-url
    type: string    
  - name: terraform-secret
    description: The terraform secret with credentials
    type: string
    default: "terraform-creds"
  - name: image
    description: the terraform image to use
    type: string
    default: datianshi/aro-terraform-oc-login:amd64
  - name: httpProxy
    description: HTTP proxy server for non-SSL requests
    type: string
    default: ""
  - name: httpsProxy
    description: HTTPS proxy server for SSL requests
    type: string
    default: ""
  - name: noProxy
    description: no proxy - opt out of proxying HTTP/HTTPS requests
    type: string
    default: ""
  results:
  - name: kubeusername
  - name: kubepassword
  - name: api-url
  steps:
    - name: init
      image: $(params.image)
      workingDir: $(workspaces.state-dir.path)
      command: ["terraform"]
      env:
        - name: "HTTP_PROXY"
          value: $(params.httpProxy)
        - name: "HTTPS_PROXY"
          value: $(params.httpsProxy)
        - name: "HTTP_PROXY"
          value: $(params.httpProxy)
      envFrom:
        - secretRef:
            name: $(params.terraform-secret)          
      args:
        - "init"
    - name: get-login-results
      image: $(params.image)
      workingDir: $(workspaces.state-dir.path)
      env:
        - name: "HTTP_PROXY"
          value: $(params.httpProxy)
        - name: "HTTPS_PROXY"
          value: $(params.httpsProxy)
        - name: "HTTP_PROXY"
          value: $(params.httpProxy)
      envFrom:
        - secretRef:
            name: $(params.terraform-secret)
      script: |
        #!/usr/bin/env sh
        eval $(params.extract-kube-admin-username) | tee $(results.kubeusername.path) 1>/dev/null
        eval $(params.extract-kube-admin-password) | tee $(results.kubepassword.path) 1>/dev/null
        eval $(params.extract-api-url) | tee $(results.api-url.path) 1>/dev/null