apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: create-openshift
spec:
  description: | 
    This pipeline creates managed OpenShift and day2 stuff
  params:
  - name: repo-url
    type: string
    description: The git repo URL to clone from.
  workspaces:
  - name: workspace
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: workspace
    params:
    - name: url
      value: $(params.repo-url)
    - name: deleteExisting
      value: "true"
  - name: terraform-plan
    runAfter:
    - fetch-source
    taskRef:
      name: terraform-cli
    workspaces:
    - name: source
      workspace: workspace
      subPath: aro
    params:
     - name: ARGS
       value:
         - plan
         - -out
         - plan_file
  - name: terraform-apply
    runAfter:
    - terraform-plan
    taskRef:
      name: terraform-cli
    workspaces:
    - name: source
      workspace: workspace
      subPath: aro
    params:
     - name: ARGS
       value:
         - apply
         - plan_file
  - name: get-oc-login
    runAfter:
    - terraform-apply
    taskRef:
      name: terraform-oc-login
    workspaces:
    - name: state-dir
      workspace: workspace
      subPath: aro
    params:
    - name: extract-kube-admin-username
      value: "terraform show -json | jq -r . | jq -r '.values.root_module.child_modules | first.resources | first.values.kubeadmin_username'"
    - name: extract-kube-admin-password
      value: "terraform show -json | jq -r . | jq -r '.values.root_module.child_modules | first.resources | first.values.kubeadmin_password'"
    - name: extract-api-url
      value: "terraform show -json | jq -r . | jq -r '.values.root_module.child_modules | first.resources | first.values.api_server_profile | first.url'"
  - name: deploy-operators
    taskRef:
      name: openshift-client
      kind: ClusterTask
    workspaces:
    - name: manifest-dir
      workspace: workspace
      subPath: operators
    params:
    - name: SCRIPT
      value: |
        oc login --server=$(tasks.get-oc-login.api-url) --username $(tasks.get-oc-login.kubeusername) --password $(tasks.get-oc-login.kubepassword)
    - name: VERSION
      value: "4.11"